### ISSUE TITLE
Ran `train.py`. But it is giving errors

### ISSUE THREAD

**Issue by PalgunaGopireddy** [yhx-hit/CVPHD#3]
```
Traceback (most recent call last):
  File "G:\Palguna\github\Autofocus_or_Denoising\Autofocus\CVPHD-main\train.py", line 15, in <module>
    from utils.visualizer import Visualizer
  File "G:\Palguna\github\Autofocus_or_Denoising\Autofocus\CVPHD-main\utils\visualizer.py", line 6, in <module>
    from . import html
  File "G:\Palguna\github\Autofocus_or_Denoising\Autofocus\CVPHD-main\utils\html.py", line 1, in <module>
    import dominate
ModuleNotFoundError: No module named 'dominate'
```
The `dominate` file is not provided?

**Comment by PalgunaGopireddy** [comment]
Got it. I thought it is a file in the directory. But installed it using `pip install dominate`

**Comment by PalgunaGopireddy** [comment]
But it is agian giving below error

```
.
.
serial_batches: False
tf_log: False
use_dropout: False
verbose: False
which_epoch: latest
-------------- End ----------------
CustomDatasetDataLoader
dataset [AlignedDataset] was created
Traceback (most recent call last):
  File "G:\Palguna\github\Autofocus_or_Denoising\Autofocus\New folder\CVPHD-main\train.py", line 39, in <module>
    data_loader = CreateDataLoader(opt)
  File "G:\Palguna\github\Autofocus_or_Denoising\Autofocus\New folder\CVPHD-main\data\data_loader.py", line 6, in CreateDataLoader
    data_loader.initialize(opt)
  File "G:\Palguna\github\Autofocus_or_Denoising\Autofocus\New folder\CVPHD-main\data\custom_dataset_data_loader.py", line 20, in initialize
    self.dataset = CreateDataset(opt)
  File "G:\Palguna\github\Autofocus_or_Denoising\Autofocus\New folder\CVPHD-main\data\custom_dataset_data_loader.py", line 11, in CreateDataset
    dataset.initialize(opt)
  File "G:\Palguna\github\Autofocus_or_Denoising\Autofocus\New folder\CVPHD-main\data\aligned_dataset.py", line 20, in initialize
    self.A_paths = sorted(make_dataset(self.dir_A))
  File "G:\Palguna\github\Autofocus_or_Denoising\Autofocus\New folder\CVPHD-main\data\image_folder.py", line 23, in make_dataset
    assert os.path.isdir(dir), '%s is not a valid directory' % dir
AssertionError: ./datasets/8class/train_A is not a valid directory
```

I didn't change any code. Please solve it.
